export const CHANGE_NAME = 'CHANGE_NAME'
export const CHANGE_LOCATION = 'CHANGE_LOCATION'

export const CHANGE_USERNAME = 'CHANGE_USERNAME'
export const CHANGE_RESPONSE_TYPE = 'CHANGE_RESPONSE_TYPE'
export const CHANGE_ALL = 'CHANGE_ALL'
